### PR TITLE
Add a CICD image with node16

### PR DESCRIPTION
**Pull request by badrange**

### CODE REVIEW

**Comment by Jancis** [comment]
If drush/drush-launcher:^0.9.1 is alright to have in the image, this change is :+1:

**Comment by badrange** [comment]
> If drush/drush-launcher:^0.9.1 is alright to have in the image, this change is +1

I just took the newest one. The older images also have drush launcher. Can revert to an older one if you want, but I'd suggest we try with this first?

**Comment by badrange** [comment]
Hi @Jancis  and thanks for the reply, good that you have eagle eyes! I reverted the change made by mistake to the node14 image and tried to create sensible tags for node16. 

Also decided to change the image path to be consistent with the earlier images.

**Comment by Jancis** [comment]
Thanks! :) I have one small change on mind, i can't find `cimg/php:8.0.13-node-composer2` image tag at https://hub.docker.com/r/cimg/php/tags?page=1&name=8.0.13-node, any chance it should have been `cimg/php:8.0.13-node` instead?

**Comment by badrange** [comment]
Hi @Jancis good that you checked, that was my mistake. Are you ok with the folder name otherwise?

**Comment by Jancis** [comment]
Yes, looks great!

**Comment by Jancis** [comment]
It did not like the drush-launcher after all

> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>    - Root composer.json requires drush/drush-launcher ^0.9.1 -> satisfiable by drush/drush-launcher[0.9.1].
>    - drush/drush-launcher 0.9.1 requires laravel-zero/phar-updater dev-main -> found laravel-zero/phar-updater[dev-main] but it > does not match your minimum-stability.

**Comment by Jancis** [comment]
I don't know too much about composer or launcher, but would this work too?
https://github.com/wunderio/silta-images/pull/5/files

**Comment by badrange** [comment]
Hi @Jancis I can test it. In our project we're not actually using drupal BUT we do have it in our silta configs.

**Comment by Jancis** [comment]
@badrange image is built

**Comment by badrange** [comment]
@Jancis thank you so much! It's already in use on one of our feature branches, seems to work well.

**Pull request merged**
